//! ABI encoding of `Bridge.executeRemoteMessages(InboundMessage[])` calldata.
//!
//! Maps the wire [`BridgeMessage`] (8 SSZ fields) into the contract-facing
//! [`InboundMessage`] (5 ABI fields), dropping `dstChainID` (implicit from execution context),
//! `mode` (re-derived locally per-token), and `srcBlock` (audit-only).

use crate::BridgeMessage;
use alloc::vec::Vec;
use alloy_primitives::{Address, Bytes, U256};
use alloy_sol_types::{sol, SolCall};

sol! {
    /// Mirrors `Bridge.sol`'s `InboundMessage` struct exactly. Field order is part of the
    /// frozen ABI; do not reorder.
    #[derive(Debug, PartialEq, Eq)]
    struct InboundMessageAbi {
        uint64 srcChainID;
        uint64 nonce;
        address localToken;
        address recipient;
        uint256 amount;
    }

    /// `Bridge.executeRemoteMessages(InboundMessage[])` — only callable from `SYSTEM_ADDRESS`.
    function executeRemoteMessages(InboundMessageAbi[] msgs) external;
}

/// Re-export for callers that want a friendlier name. The Solidity ABI struct generated by
/// `sol!` is usable directly, but tests / conversion helpers prefer the alias.
pub type InboundMessage = InboundMessageAbi;

/// Builds the full `Bridge.executeRemoteMessages([...])` ABI calldata payload.
///
/// * Filters out any [`BridgeMessage`] whose `dst_chain_id` does not match `local_chain_id`.
///   In practice CL always pre-filters; this is defence-in-depth so a misrouted message can't
///   make the system call execute on the wrong chain.
/// * Drops `dst_chain_id`, `mode`, `src_block` per the schema freeze §"CL→EL 字段映射".
/// * Converts `amount` from big-endian `Bytes32` into `U256`.
/// * Preserves message ordering (CL has already sorted by `(SrcCID, DstCID, Nonce)`).
///
/// Returns the 4-byte selector + ABI-encoded args, ready to be passed as the `calldata`
/// argument of `Evm::transact_system_call`.
pub fn encode_execute_remote_messages_calldata(
    msgs: &[BridgeMessage],
    local_chain_id: u64,
) -> Bytes {
    let abi_msgs: Vec<InboundMessageAbi> = msgs
        .iter()
        .filter(|m| m.dst_chain_id == local_chain_id)
        .map(|m| InboundMessageAbi {
            srcChainID: m.src_chain_id,
            nonce: m.nonce,
            localToken: Address::from(m.local_token.0),
            recipient: Address::from(m.recipient.0),
            amount: U256::from_be_bytes::<32>(m.amount.0),
        })
        .collect();

    let call = executeRemoteMessagesCall { msgs: abi_msgs };
    Bytes::from(call.abi_encode())
}

#[cfg(test)]
mod tests {
    use super::*;
    use alloy_primitives::FixedBytes;
    use alloy_sol_types::SolCall;

    fn msg_for(src: u64, dst: u64, nonce: u64) -> BridgeMessage {
        BridgeMessage {
            src_chain_id: src,
            dst_chain_id: dst,
            nonce,
            local_token: FixedBytes([0xaa; 20]),
            recipient: FixedBytes([0xbb; 20]),
            amount: FixedBytes(U256::from(123_456_789u64).to_be_bytes::<32>()),
            mode: 0,
            src_block: 100,
        }
    }

    #[test]
    fn empty_input_produces_empty_array_calldata() {
        let cd = encode_execute_remote_messages_calldata(&[], 16700);
        // Should still be a valid call (selector + empty array).
        assert!(cd.len() >= 4, "must contain selector");
        let decoded = executeRemoteMessagesCall::abi_decode(&cd).expect("roundtrip empty");
        assert!(decoded.msgs.is_empty());
    }

    #[test]
    fn dst_chain_filter_drops_mismatched_messages() {
        let msgs = vec![
            msg_for(1, 16700, 1),
            msg_for(1, 99999, 2), // foreign destination — should be filtered
            msg_for(1, 16700, 3),
        ];
        let cd = encode_execute_remote_messages_calldata(&msgs, 16700);
        let decoded = executeRemoteMessagesCall::abi_decode(&cd).expect("roundtrip");
        assert_eq!(decoded.msgs.len(), 2);
        assert_eq!(decoded.msgs[0].nonce, 1);
        assert_eq!(decoded.msgs[1].nonce, 3);
    }

    #[test]
    fn abi_roundtrip_preserves_all_carried_fields() {
        let m = BridgeMessage {
            src_chain_id: 16700,
            dst_chain_id: 16702,
            nonce: 42,
            local_token: FixedBytes([0x11; 20]),
            recipient: FixedBytes([0x22; 20]),
            amount: FixedBytes(
                U256::from(1_000_000_000_000_000_000u128).to_be_bytes::<32>(),
            ),
            mode: 1,
            src_block: 7,
        };
        let cd = encode_execute_remote_messages_calldata(&[m.clone()], 16702);
        let decoded = executeRemoteMessagesCall::abi_decode(&cd).expect("roundtrip");
        assert_eq!(decoded.msgs.len(), 1);
        let am = &decoded.msgs[0];
        assert_eq!(am.srcChainID, 16700);
        assert_eq!(am.nonce, 42);
        assert_eq!(am.localToken, Address::from([0x11; 20]));
        assert_eq!(am.recipient, Address::from([0x22; 20]));
        assert_eq!(am.amount, U256::from(1_000_000_000_000_000_000u128));
    }

    #[test]
    fn calldata_starts_with_execute_remote_messages_selector() {
        let m = msg_for(1, 16700, 1);
        let cd = encode_execute_remote_messages_calldata(&[m], 16700);
        let expected_selector = executeRemoteMessagesCall::SELECTOR;
        assert_eq!(&cd[..4], &expected_selector);
    }

    #[test]
    fn abi_field_order_matches_solidity() {
        // (uint64 srcChainID, uint64 nonce, address localToken, address recipient, uint256
        // amount) — verified by encoding then checking the typed decode succeeds. Field
        // misordering would surface as a decode error or wrong values.
        let m = msg_for(123, 16700, 9);
        let cd = encode_execute_remote_messages_calldata(&[m], 16700);
        let decoded = executeRemoteMessagesCall::abi_decode(&cd).unwrap();
        assert_eq!(decoded.msgs[0].srcChainID, 123);
        assert_eq!(decoded.msgs[0].nonce, 9);
    }
}
